### ISSUE TITLE
Support for Python 3.2

### ISSUE THREAD

**Issue by fschaller** [domenkozar/almir#36]
Install script does not run on Python 3.2. Please consider Python 3.2 support.

Thanks.

**Comment by domenkozar** [comment]
There are no plans to support Python 3 in near future, but eventually there will be! What is your use case? Why can't you use Python 2?

**Comment by fschaller** [comment]
Python 3.2 is installed (it's a gentoo system) and I don't like to replace it with 2.7, because gentoo system tools are based on Python and I have no idea if they will still work with 2.7.

**Comment by domenkozar** [comment]
I have a few Gentoo installations and Python 2.7 runs just fine, I would recommend using that. Maybe I should add support to choose which python binary to run on install.

For now you can run commands from installer script manually, but with replace line:

python bootstrap.py

with:

python2.7 bootstrap.py

**Comment by fschaller** [comment]
Ok, I installed python 2.7 and will try to run the script like that. Your response time is awesome ;-)!

**Comment by domenkozar** [comment]
I'm always glad I can help :) Here are the install steps: https://raw.github.com/iElectric/almir/master/install_production.sh

**Comment by fschaller** [comment]
Thank you - sorry, completely new to Python. Where can I set postgresql for the database connection? I get following error:

Getting distribution for 'pysqlite==2.6.0'.
In file included from src/module.c:24:0:
src/connection.h:33:21: fatal error: sqlite3.h: No such file or directory

**Comment by domenkozar** [comment]
I'm afraid you will have to recompile python 2.7 with sqlite flag, it assumes python is compiled with that flag. I will add this to documentation, thanks!

**Comment by fschaller** [comment]
Unbelievable! It works! Even for a Python dummy as me easy to setup! You have built a great product! Thank you very much!

**Comment by fschaller** [comment]
For all gentoo users out here: steps to setup almir:

emerge dev-lang/python:2.7
emerge dev-python/pysqlite
mkdir /var/almir
cd /var/almir
sh -xec "$(wget -O - https://raw.github.com/iElectric/almir/master/install_production.sh)"
Python 3.2 error will occur
python2.7 bootstrap.py
bin/buildout
bin/python almir/scripts/configure_deploy.py
bin/buildout -o
bin/supervisord
set +xe

After this almir is working. I will close the issue. Great work!
